image: Visual Studio 2017

platform:
  - x64

install:
  - ps: Start-FileDownload 'https://github.com/mongodb/mongo-c-driver/releases/download/1.14.0/mongo-c-driver-1.14.0.tar.gz'

build_script:
  - tar xf mongo-c-driver-1.14.0.tar.gz
  - cd mongo-c-driver-1.14.0
  - mkdir cmake-build
  - cd cmake-build
  - cmake -G "Visual Studio 15 2017" "-DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/target" "-DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%/target" ..
  - msbuild.exe /p:Configuration=RelWithDebInfo ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - cd %APPVEYOR_BUILD_FOLDER%/target
  - tar -zcvf ../mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz *

artifacts:
  - path: .\mongo-c-driver-builder.v1.14.0.x86_64-windows.tar.gz
    name: tarball
    type: File

deploy:
  description: 'libmongoc driver for windows x86_64'
  provider: GitHub
  auth_token:
    secure: oju7dP5xizhRhVzfp+o4vdl+eI2UplzGv5n8H4t+nCGvokaHQsNipRYlGRUZUyR6
  artifact: tarball
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
