
platform:
  - x64

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
#  - bash -lc "pacman --noconfirm -Syu"
#  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake"
#  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-extra-cmake-modules make tar"
#  - bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-cyrus-sasl"
  - ps: Start-FileDownload 'https://github.com/mongodb/mongo-c-driver/releases/download/1.14.0/mongo-c-driver-1.14.0.tar.gz'

build_script:
  - tar xf mongo-c-driver-1.14.0.tar.gz
  - cd mongo-c-driver-1.14.0
  - CC=/mingw64/bin/gcc.exe /mingw64/bin/cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/target" .
  - make
  - cd %APPVEYOR_BUILD_FOLDER%/target
  - tar -zcvf ../mongo-c-driver-builder.v1.14.0.mingw-w64-x86_64.tar.gz *

artifacts:
  - path: .\mongo-c-driver-builder.v1.14.0.mingw-w64-x86_64.tar.gz
    name: tarball
    type: File

deploy:
  description: 'libmongoc driver for windows x86_64'
  provider: GitHub
  auth_token:
    secure: oju7dP5xizhRhVzfp+o4vdl+eI2UplzGv5n8H4t+nCGvokaHQsNipRYlGRUZUyR6
  artifact: tarball
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true